
from io import BytesIO
import re

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


# --------------------------------
# Clean Gemini Markdown
# --------------------------------

def clean_markdown(text):

    if not text:
        return ""

    # Remove markdown headings
    text = re.sub(r'#{1,6}\s*', '', text)

    # Remove bold (**text**)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)

    # Remove italic (*text*)
    text = re.sub(r'\*(.*?)\*', r'\1', text)

    # Remove remaining markdown chars
    text = text.replace("*", "")
    text = text.replace("#", "")
    text = text.replace("`", "")
    text = text.replace("_", "")

    # Remove blockquotes
    text = text.replace(">", "")

    # Clean extra spaces
    text = re.sub(r'\n{3,}', '\n\n', text)

    return text.strip()


# --------------------------------
# PDF Generator
# --------------------------------

def create_pdf_report(score, feedback):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    # Clean Gemini output
    feedback = clean_markdown(feedback)

    # --------------------------------
    # Title
    # --------------------------------

    story.append(
        Paragraph(
            "GENAI Resume Analysis Report",
            styles["Title"]
        )
    )

    story.append(
        Spacer(1, 20)
    )

    # --------------------------------
    # Score Section
    # --------------------------------

    story.append(
        Paragraph(
            "Resume Match Score",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"<b>{score}%</b>",
            styles["BodyText"]
        )
    )

    story.append(
        Spacer(1, 15)
    )

    # --------------------------------
    # Summary
    # --------------------------------

    story.append(
        Paragraph(
            "Gen AI Analysis Summary",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"The uploaded resume achieved a match score of {score}% against the provided job description.",
            styles["BodyText"]
        )
    )

    story.append(
        Spacer(1, 15)
    )

    # --------------------------------
    # Gemini Feedback
    # --------------------------------

    story.append(
        Paragraph(
            "Gemini Feedback",
            styles["Heading2"]
        )
    )

    feedback = feedback.replace(
        "\n",
        "<br/>"
    )

    story.append(
        Paragraph(
            feedback,
            styles["BodyText"]
        )
    )

    story.append(
        Spacer(1, 20)
    )

    # --------------------------------
    # Recommendations
    # --------------------------------

    story.append(
        Paragraph(
            "General Recommendations",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            """
            • Tailor your resume to the target role.<br/>
            • Highlight measurable achievements.<br/>
            • Include relevant technical skills.<br/>
            • Quantify project outcomes wherever possible.<br/>
            • Use ATS-friendly formatting.
            """,
            styles["BodyText"]
        )
    )

    story.append(
        Spacer(1, 20)
    )

    # --------------------------------
    # Footer
    # --------------------------------

    story.append(
        Paragraph(
            "Generated by AI Resume Analyzer",
            styles["Italic"]
        )
    )

    # --------------------------------
    # Build PDF
    # --------------------------------

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf

